development:
  adapter: postgresql
  database: recipe_development
  host: localhost
  username: rrgayhart
  password:

test:
  adapter: postgresql
  database: recipe_test
  host: localhost
  username: rrgayhart
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: recipe_production
  pool: 5
  username: u
